import type { AppSchema, RuntimeOutput } from "../schemas.js";

// ─── SQL DDL Generator ───────────────────────────────────────────────────────

export function generateSQL(schema: AppSchema): string {
  const lines: string[] = ["-- Auto-generated by AppGen Runtime", "PRAGMA foreign_keys = ON;", ""];

  for (const table of schema.db_schema.tables) {
    lines.push(`CREATE TABLE IF NOT EXISTS "${table.name}" (`);

    const colDefs = table.columns.map((col) => {
      let def = `  "${col.name}" ${col.type}`;
      if (col.primary_key) def += " PRIMARY KEY";
      if (col.not_null) def += " NOT NULL";
      if (col.unique) def += " UNIQUE";
      if (col.default_value != null) def += ` DEFAULT '${col.default_value}'`;
      if (col.references) {
        def += ` REFERENCES "${col.references.table}"("${col.references.column}")`;
      }
      return def;
    });

    lines.push(colDefs.join(",\n"));
    lines.push(");");

    for (const idx of table.indexes) {
      const unique = idx.unique ? "UNIQUE " : "";
      const cols = idx.columns.map((c) => `"${c}"`).join(", ");
      lines.push(
        `CREATE ${unique}INDEX IF NOT EXISTS "idx_${table.name}_${idx.columns.join("_")}" ON "${table.name}" (${cols});`
      );
    }

    lines.push("");
  }

  return lines.join("\n");
}

// ─── Express Routes Generator ────────────────────────────────────────────────

export function generateExpressRoutes(schema: AppSchema): string {
  const endpoints = schema.api_schema.endpoints;
  const lines: string[] = [
    "// Auto-generated Express routes by AppGen Runtime",
    "import express from 'express';",
    "import Database from 'better-sqlite3';",
    "import { v4 as uuidv4 } from 'uuid';",
    "",
    "export function registerRoutes(app: express.Application, db: Database.Database) {",
    "",
  ];

  for (const ep of endpoints) {
    const method = ep.method.toLowerCase();
    const hasId = ep.path.includes(":id");
    const table = ep.db_table || "";
    const authCheck = ep.auth_required
      ? `  // Auth required: ${ep.roles.length ? ep.roles.join(", ") : "any authenticated user"}\n  if (!req.user) return res.status(401).json({ error: "Unauthorized" });\n`
      : "";

    lines.push(`  // ${ep.summary}`);
    lines.push(`  app.${method}('${schema.api_schema.base_path}${ep.path}', (req, res) => {`);
    lines.push(`    try {`);
    if (authCheck) lines.push("    " + authCheck);

    if (table) {
      if (ep.method === "GET" && !hasId) {
        lines.push(`      const rows = db.prepare('SELECT * FROM "${table}"').all();`);
        lines.push(`      res.json({ data: rows, total: rows.length });`);
      } else if (ep.method === "GET" && hasId) {
        lines.push(`      const row = db.prepare('SELECT * FROM "${table}" WHERE id = ?').get(req.params.id);`);
        lines.push(`      if (!row) return res.status(404).json({ error: 'Not found' });`);
        lines.push(`      res.json(row);`);
      } else if (ep.method === "POST") {
        const fields = ep.request_body ? Object.keys(ep.request_body) : [];
        if (fields.length > 0) {
          const cols = ["id", ...fields, "created_at", "updated_at"]
            .map((f) => `"${f}"`)
            .join(", ");
          const placeholders = ["?", ...fields.map(() => "?"), "datetime('now')", "datetime('now')"].join(", ");
          lines.push(`      const id = uuidv4();`);
          lines.push(`      const { ${fields.join(", ")} } = req.body;`);
          lines.push(
            `      db.prepare('INSERT INTO "${table}" (${cols}) VALUES (${placeholders})').run(id, ${fields.join(", ")});`
          );
          lines.push(`      res.status(201).json({ id, message: 'Created' });`);
        } else {
          lines.push(`      const id = uuidv4();`);
          lines.push(
            `      db.prepare('INSERT INTO "${table}" (id, created_at, updated_at) VALUES (?, datetime("now"), datetime("now"))').run(id);`
          );
          lines.push(`      res.status(201).json({ id });`);
        }
      } else if (ep.method === "PUT" || ep.method === "PATCH") {
        const fields = ep.request_body ? Object.keys(ep.request_body) : [];
        if (fields.length > 0) {
          const sets = [...fields.map((f) => `"${f}" = ?`), `"updated_at" = datetime('now')`].join(", ");
          lines.push(`      const { ${fields.join(", ")} } = req.body;`);
          lines.push(
            `      const info = db.prepare('UPDATE "${table}" SET ${sets} WHERE id = ?').run(${fields.join(", ")}, req.params.id);`
          );
          lines.push(`      if (!info.changes) return res.status(404).json({ error: 'Not found' });`);
          lines.push(`      res.json({ message: 'Updated' });`);
        } else {
          lines.push(`      res.json({ message: 'Updated' });`);
        }
      } else if (ep.method === "DELETE") {
        lines.push(
          `      const info = db.prepare('DELETE FROM "${table}" WHERE id = ?').run(req.params.id);`
        );
        lines.push(`      if (!info.changes) return res.status(404).json({ error: 'Not found' });`);
        lines.push(`      res.json({ message: 'Deleted' });`);
      }
    } else {
      lines.push(`      res.json({ message: '${ep.summary}', status: 'ok' });`);
    }

    lines.push(`    } catch (err: any) {`);
    lines.push(`      res.status(500).json({ error: err.message });`);
    lines.push(`    }`);
    lines.push(`  });`);
    lines.push(``);
  }

  lines.push("}");
  return lines.join("\n");
}

// ─── HTML Pages Generator ────────────────────────────────────────────────────

export function generateHTMLPages(schema: AppSchema): Record<string, string> {
  const pages: Record<string, string> = {};

  for (const page of schema.ui_schema.pages) {
    const componentsHTML = page.components
      .map((comp) => {
        if (comp.type === "form") {
          const fields = comp.fields
            .map(
              (f) => `
        <div class="field">
          <label for="${f.name}">${f.label}${f.required ? " *" : ""}</label>
          ${
            f.input_type === "select"
              ? `<select id="${f.name}" name="${f.name}" ${f.required ? "required" : ""}>
            ${(f.options || []).map((o) => `<option value="${o}">${o}</option>`).join("")}
          </select>`
              : f.input_type === "textarea"
              ? `<textarea id="${f.name}" name="${f.name}" ${f.required ? "required" : ""}></textarea>`
              : `<input type="${f.input_type}" id="${f.name}" name="${f.name}" ${f.required ? "required" : ""} />`
          }
        </div>`
            )
            .join("\n");

          return `<div class="component form-component">
      <h3>${comp.label}</h3>
      <form id="form-${comp.label.replace(/\s+/g, "-").toLowerCase()}" data-endpoint="${comp.api_endpoint || ""}">
        ${fields}
        <button type="submit" class="btn-primary">Submit</button>
      </form>
    </div>`;
        }

        if (comp.type === "table") {
          return `<div class="component table-component">
      <h3>${comp.label}</h3>
      <div class="table-actions">
        <input type="text" placeholder="Search..." class="search-input" />
      </div>
      <table id="table-${comp.label.replace(/\s+/g, "-").toLowerCase()}" data-endpoint="${comp.api_endpoint || ""}">
        <thead><tr><th>Loading...</th></tr></thead>
        <tbody></tbody>
      </table>
    </div>`;
        }

        if (comp.type === "stat") {
          return `<div class="component stat-component">
      <div class="stat-card"><span class="stat-label">${comp.label}</span><span class="stat-value" id="stat-${comp.label.replace(/\s+/g, "-").toLowerCase()}">—</span></div>
    </div>`;
        }

        return `<div class="component"><h3>${comp.label}</h3></div>`;
      })
      .join("\n");

    pages[page.path] = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${page.title} — ${schema.ui_schema.app_name}</title>
  <style>
    * { box-sizing: border-box; margin: 0; padding: 0; }
    body { font-family: system-ui, sans-serif; background: #f8fafc; color: #1e293b; }
    nav { background: #0f172a; color: white; padding: 1rem 2rem; display: flex; gap: 1.5rem; align-items: center; }
    nav a { color: #94a3b8; text-decoration: none; font-size: 0.875rem; } nav a:hover { color: white; }
    .page-header { padding: 2rem; border-bottom: 1px solid #e2e8f0; background: white; }
    .page-header h1 { font-size: 1.5rem; font-weight: 700; }
    .content { padding: 2rem; max-width: 1200px; }
    .component { background: white; border: 1px solid #e2e8f0; border-radius: 8px; padding: 1.5rem; margin-bottom: 1.5rem; }
    .field { margin-bottom: 1rem; }
    label { display: block; font-size: 0.875rem; font-weight: 500; color: #475569; margin-bottom: 0.25rem; }
    input, select, textarea { width: 100%; padding: 0.5rem 0.75rem; border: 1px solid #cbd5e1; border-radius: 6px; font-size: 0.875rem; }
    .btn-primary { background: #3b82f6; color: white; padding: 0.5rem 1.25rem; border: none; border-radius: 6px; cursor: pointer; font-size: 0.875rem; }
    .btn-primary:hover { background: #2563eb; }
    table { width: 100%; border-collapse: collapse; font-size: 0.875rem; }
    th, td { padding: 0.75rem 1rem; text-align: left; border-bottom: 1px solid #f1f5f9; }
    th { background: #f8fafc; font-weight: 600; color: #475569; }
    .search-input { padding: 0.5rem 0.75rem; border: 1px solid #cbd5e1; border-radius: 6px; margin-bottom: 1rem; width: 300px; }
    .stat-card { text-align: center; padding: 1rem; }
    .stat-label { display: block; font-size: 0.75rem; color: #64748b; text-transform: uppercase; letter-spacing: 0.05em; }
    .stat-value { display: block; font-size: 2rem; font-weight: 700; color: #0f172a; margin-top: 0.25rem; }
  </style>
</head>
<body>
  <nav>
    <strong style="color:white;margin-right:1rem">${schema.ui_schema.app_name}</strong>
    ${schema.ui_schema.nav_items.map((n) => `<a href="${n.path}">${n.label}</a>`).join("")}
  </nav>
  <div class="page-header"><h1>${page.title}</h1></div>
  <div class="content">
    ${componentsHTML}
  </div>
  <script>
    // Auto-load table data
    document.querySelectorAll('table[data-endpoint]').forEach(async (table) => {
      const endpoint = table.getAttribute('data-endpoint');
      if (!endpoint) return;
      try {
        const res = await fetch(endpoint);
        const json = await res.json();
        const rows = json.data || (Array.isArray(json) ? json : [json]);
        if (rows.length > 0) {
          const keys = Object.keys(rows[0]);
          table.querySelector('thead tr').innerHTML = keys.map(k => \`<th>\${k}</th>\`).join('');
          table.querySelector('tbody').innerHTML = rows.map(r => \`<tr>\${keys.map(k => \`<td>\${r[k] ?? ''}</td>\`).join('')}</tr>\`).join('');
        }
      } catch(e) { console.warn('Could not load table data:', e); }
    });

    // Auto-submit forms
    document.querySelectorAll('form[data-endpoint]').forEach(form => {
      form.addEventListener('submit', async (e) => {
        e.preventDefault();
        const endpoint = form.getAttribute('data-endpoint');
        if (!endpoint) return;
        const data = Object.fromEntries(new FormData(form));
        try {
          const res = await fetch(endpoint, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(data) });
          const json = await res.json();
          alert(json.message || 'Success!');
        } catch(e) { alert('Error: ' + e); }
      });
    });
  </script>
</body>
</html>`;
  }

  return pages;
}

// ─── Simulate Runtime Execution ──────────────────────────────────────────────

export function simulateRuntime(schema: AppSchema): RuntimeOutput {
  const tables_created = schema.db_schema.tables.map((t) => t.name);
  const routes_registered = schema.api_schema.endpoints.map(
    (e) => `${e.method} ${schema.api_schema.base_path}${e.path}`
  );
  const pages_generated = schema.ui_schema.pages.map((p) => p.path);

  return { tables_created, routes_registered, pages_generated };
}
